### ISSUE TITLE
Can't find armature on avatars which does not follow the naming convention "Armature" (e.g. Ash)

### ISSUE THREAD

**Issue by alzahhar3** [poi-vrc/DressingTools#10]
Ash's armeture is literally just called "Ash", I assume that is throwing it off and it can't find the armature

**Comment by poi-vrc** [comment]
Thanks for notifying that! I didn't know some of the avatars do not follow the naming convention (Armature) at all, which is not a good practice I guess.

Can you do me a favour to take a screenshot of the Ash's avatar structure and send it to here? I will try to think for a workaround and release as a fix.

**Comment by poi-vrc** [comment]
I want a screenshot like this:

![image](https://user-images.githubusercontent.com/77053052/168753857-c102e380-09c8-4773-a349-39811fd5b06c.png)

**Comment by alzahhar3** [comment]
yeah here is what it looks like
[image: image.png]

**Comment by poi-vrc** [comment]
Sorry, I can't see the photo, can you reupload it in GitHub's website?

**Comment by poi-vrc** [comment]
Sorry but you have to send the photo to me again, as there is no photo you sent can be seen here. Otherwise I could not make a workaround to deal with this issue.

**Comment by alzahhar3** [comment]
![image](https://user-images.githubusercontent.com/80571766/170924317-7cb8a8c3-9e1a-4b5b-9c33-faa457410e2f.png)
Sorry forgot to send again, here is the photo.

**Comment by poi-vrc** [comment]
planned to add custom armature object name

**Comment by poi-vrc** [comment]
Added implementation for custom armature object name, currently missing UI option

**Comment by poi-vrc** [comment]
Added UI option for using custom Avatar and Clothes armature object name, closing issue. https://github.com/poi-vrc/DressingTools/commit/1dad448fb9362484dc2a02ecf39f54efd26ef84f
