### ISSUE TITLE
rename bug and then won't find armature

### ISSUE THREAD

**Issue by megu84844** [poi-vrc/DressingTools#14]
![d8f6fd48d503398c682b0d4befcdd0eb](https://user-images.githubusercontent.com/104563520/181618230-66b7af69-b87d-4eb8-b6ea-9c1f0f2eee1b.png)

please fix this for japanese characters
even if you rename it , the tool can't find armature afterwards when you click dress now.
it will not dress completely

**Comment by poi-vrc** [comment]
Hi, can you send the whole Dress Report generated below this section after pressing the "Rename" button?

P.S. this tool blocks non-English characters (aka non-ASCII characters) for preparation for the Cabinet system in the v2 version. Because non-ASCII characters might cause problems. I might be able to allow these characters in future versions but I certainly don't recomemnd using them.

**Comment by megu84844** [comment]
![e5f6330f3eeadd6593063e01d04e846f](https://user-images.githubusercontent.com/104563520/181800485-fc84bc53-227b-479a-a6c0-40995a62a3a6.png)

this

**Comment by megu84844** [comment]
it's time consuming to rename japanese to english xd  in suffix and prefix

**Comment by poi-vrc** [comment]
I understand, let me try removing that requirement in future releases.

> even if you rename it , the tool can't find armature afterwards when you click dress now.
> it will not dress completely

 Can you also send me the Dress Report when dressing this clothes? It should be able to find the armature after clicking "Rename". If it does not, it would be a weird bug.

**Comment by poi-vrc** [comment]
Planned to support non-ASCII characters

**Comment by mob41** [comment]
changed the error to be warning in 1.2.0-nightly

**Comment by poi-vrc** [comment]
not a error anymore in 1.2.0-nightly, warning only now.

**Comment by poi-vrc** [comment]
![image](https://user-images.githubusercontent.com/77053052/194845348-16e3a038-1c6b-4528-a8bc-8e1196dac3a0.png)
To use the latest builds, change update branch to "nightly"
