### ISSUE TITLE
In game, different clothes overlap each other

### ISSUE THREAD

**Issue by oniyakun** [poi-vrc/DressingTools#291]
Switching between different clothes in unity works fine in the test, but in the game the different clothes overlap each other. Im using the latest version of DressingTools and 2019.4.31f1 of unity

**Comment by oniyakun** [comment]
Includes from my friends says, this bug appears only happens to myself, it shows perfectly fine to all my other friends.

**Comment by poi-vrc** [comment]
Hi, I would like to know do you have any other animations controlling those objects? There might be some non-synced parameters controlling those objects.
