### ISSUE TITLE
After install there's only DK Report Window in the tools menu.

### ISSUE THREAD

**Issue by XKaguya** [poi-vrc/DressingTools#371]
As title. My package folder:

![image](https://github.com/poi-vrc/DressingTools/assets/96401952/a8da3359-96b9-445a-91ab-184313bfa514)

It used to raise NDMF version error. And after i grab a 1.3.7 one, it keeps says that missing packages and wont download automaticly or show (if i click the show missing).

AvatarLib, DressingFramework, DressingTools were all the newest version.

**Comment by poi-vrc** [comment]
What kind of missing packages error is that? Can you screenshot the dialog? Thanks.

**Comment by XKaguya** [comment]
> What kind of missing packages error is that? Can you screenshot the dialog? Thanks.

Sure, a sec letme restart my unity

**Comment by poi-vrc** [comment]
Also please provide a list of packages with versions that you have installed. Thanks.

**Comment by XKaguya** [comment]
> Also please provide a list of packages with versions that you have installed. Thanks.

I'm used to install with zips. Which means i can only give you the json list. Sry if that bother you

```
{
  "dependencies": {
    "com.vrchat.core.vpm-resolver": {
      "version": "0.1.26"
    },
    "com.vrchat.avatars": {
      "version": "3.4.1"
    },
    "dev.vrlabs.av3manager": {
      "version": "2.0.25"
    },
    "nadena.dev.modular-avatar": {
      "version": "1.8.1"
    },
    "vrchat.blackstartx.gesture-manager": {
      "version": "3.8.7"
    }
  },
  "locked": {
    "com.vrchat.core.vpm-resolver": {
      "version": "0.1.26",
      "dependencies": {}
    },
    "com.vrchat.avatars": {
      "version": "3.4.1",
      "dependencies": {
        "com.vrchat.base": "3.4.1"
      }
    },
    "com.vrchat.base": {
      "version": "3.4.1",
      "dependencies": {}
    },
    "dev.vrlabs.av3manager": {
      "version": "2.0.25",
      "dependencies": {
        "com.vrchat.avatars": ">=3.2.0 < 3.5.0"
      }
    },
    "nadena.dev.modular-avatar": {
      "version": "1.8.1",
      "dependencies": {
        "com.vrchat.avatars": ">=3.2.0",
        "nadena.dev.ndmf": ">=1.1.1 <2.0.0-a"
      }
    },
    "nadena.dev.ndmf": {
      "version": "1.3.7",
      "dependencies": {}
    },
    "vrchat.blackstartx.gesture-manager": {
      "version": "3.8.7",
      "dependencies": {
        "com.vrchat.avatars": "3.2.x || 3.3.x || 3.4.x"
      }
    }
  }
}
```
And the dialog:
![image](https://github.com/poi-vrc/DressingTools/assets/96401952/d09cc23b-84dd-44e2-a147-f17658007db2)
![image](https://github.com/poi-vrc/DressingTools/assets/96401952/a46e0148-22b7-45c6-878b-18c737585362)

**Comment by XKaguya** [comment]
> > Also please provide a list of packages with versions that you have installed. Thanks.
> 
> I'm used to install with zips. Which means i can only give you the json list. Sry if that bother you
> 
> ```
> {
>   "dependencies": {
>     "com.vrchat.core.vpm-resolver": {
>       "version": "0.1.26"
>     },
>     "com.vrchat.avatars": {
>       "version": "3.4.1"
>     },
>     "dev.vrlabs.av3manager": {
>       "version": "2.0.25"
>     },
>     "nadena.dev.modular-avatar": {
>       "version": "1.8.1"
>     },
>     "vrchat.blackstartx.gesture-manager": {
>       "version": "3.8.7"
>     }
>   },
>   "locked": {
>     "com.vrchat.core.vpm-resolver": {
>       "version": "0.1.26",
>       "dependencies": {}
>     },
>     "com.vrchat.avatars": {
>       "version": "3.4.1",
>       "dependencies": {
>         "com.vrchat.base": "3.4.1"
>       }
>     },
>     "com.vrchat.base": {
>       "version": "3.4.1",
>       "dependencies": {}
>     },
>     "dev.vrlabs.av3manager": {
>       "version": "2.0.25",
>       "dependencies": {
>         "com.vrchat.avatars": ">=3.2.0 < 3.5.0"
>       }
>     },
>     "nadena.dev.modular-avatar": {
>       "version": "1.8.1",
>       "dependencies": {
>         "com.vrchat.avatars": ">=3.2.0",
>         "nadena.dev.ndmf": ">=1.1.1 <2.0.0-a"
>       }
>     },
>     "nadena.dev.ndmf": {
>       "version": "1.3.7",
>       "dependencies": {}
>     },
>     "vrchat.blackstartx.gesture-manager": {
>       "version": "3.8.7",
>       "dependencies": {
>         "com.vrchat.avatars": "3.2.x || 3.3.x || 3.4.x"
>       }
>     }
>   }
> }
> ```
> 
> And the dialog: ![image](https://private-user-images.githubusercontent.com/96401952/313039162-d09cc23b-84dd-44e2-a147-f17658007db2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NjY2NTAsIm5iZiI6MTcxMDQ2NjM1MCwicGF0aCI6Ii85NjQwMTk1Mi8zMTMwMzkxNjItZDA5Y2MyM2ItODRkZC00NGUyLWExNDctZjE3NjU4MDA3ZGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDAxMzIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzN2NjMWQ0OTY3YTkwMzUwZTczZTUxYTY2OWIyYzI3M2ViZDMzOWExZWI4MDE3N2M5ZTdkNGRlNjg4Nzg3ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7pbw6sbN54rjNSCxpsz_Wkn9Hz88YqTgIFlCQ7m5ZAc) ![image](https://private-user-images.githubusercontent.com/96401952/313039172-a46e0148-22b7-45c6-878b-18c737585362.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NjY2NTAsIm5iZiI6MTcxMDQ2NjM1MCwicGF0aCI6Ii85NjQwMTk1Mi8zMTMwMzkxNzItYTQ2ZTAxNDgtMjJiNy00NWM2LTg3OGItMThjNzM3NTg1MzYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDAxMzIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZTkzYWNhOGQwNWNkMDNiZjFkZmQ1NDQ0MzYzNDdjOGZmMzdjMDMxMDhkZDZkM2ZmOTYxMTJjM2EzZGNjYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0XhBG08fMXe5Sz_64gBkdcRcioIY3l23H3nfHueia1I)

And this time i've deleted 
![image](https://github.com/poi-vrc/DressingTools/assets/96401952/d89b16f1-70ea-4e96-91a9-900eebb10e88)
Now the tools have no DressingTools section, only the NDMF
![Uploading image.png…]()

**Comment by poi-vrc** [comment]
I think you have only update some of the DressingTools packages.

You need the latest version of DressingTools (2.2.1) and DressingFramework (2.1.0). Old versions might not work properly with each other.

I guess that’s why VPM resolver keep popping out. You are still recommended to use VPM for updates.

**Comment by XKaguya** [comment]
> I think you have only update some of the DressingTools packages.
> 
> You need the latest version of DressingTools (2.2.1) and DressingFramework (2.1.0). Old versions might not work properly with each other.
> 
> I guess that’s why VPM resolver keep popping out. You are still recommended to use VPM for updates.

lol i have no VPM so thats why im using the zip. Thanks i'll have a try. I'm new for this

**Comment by XKaguya** [comment]
> I think you have only update some of the DressingTools packages.
> 
> You need the latest version of DressingTools (2.2.1) and DressingFramework (2.1.0). Old versions might not work properly with each other.
> 
> I guess that’s why VPM resolver keep popping out. You are still recommended to use VPM for updates.

It solved. I've deleted the package inside the Assets, and changed all the DressingTools, But which comes a new issue:
![image](https://github.com/poi-vrc/DressingTools/assets/96401952/6c28e6a4-c9b8-4d89-a5de-03e35cf19c32)

Is this my avatar missing something or my clothes have issues ?

**Comment by mob41** [comment]
I think your avatar/clothes require some kind of scripts. Please either search that object and then delete the missing scripts, or import the related stuff. Otherwise it can’t upload.

**Comment by poi-vrc** [comment]
Yes, you have some scripts missing in your avatar/clothes. Locate the object and either delete the missing script (not recommended) or import the script (by finding the related booth pages etc)

**Comment by XKaguya** [comment]
> Yes, you have some scripts missing in your avatar/clothes. Locate the object and either delete the missing script (not recommended) or import the script (by finding the related booth pages etc)

Thank you very much. Does another error were related about the script error too ?

**Comment by poi-vrc** [comment]
Yup, it will disappear when the one above is fixed. these kinds of error reporting will be improved later on.

**Comment by XKaguya** [comment]
> Yup, it will disappear when the one above is fixed. these kinds of error reporting will be improved later on.

Thanks !
