### ISSUE TITLE
Automatically Generate Additional Pages in the Cabinet System for More Than 7 Items

### ISSUE THREAD

**Issue by CuteLuoBo** [poi-vrc/DressingTools#428]
Currently, the cabinet system only displays the first 7 items when more are added, requiring users to manually reduce the number of items. We need an automatic pagination feature to support more than 7 items.
![2024](https://github.com/poi-vrc/DressingTools/assets/44561136/236be58f-f1b8-427a-b3dc-433aeb1556a6)
![20240613](https://github.com/poi-vrc/DressingTools/assets/44561136/3877e660-9537-4cef-afd0-a844e8d363a2)

**Comment by poi-vrc** [comment]
It should automatically paginate with a "Next" once the 7-th item is created. Are you sure that the missing items have cabinet animations enabled?
