### ISSUE TITLE
Exporting Photos Taken in the Cabinet System for Use as Icons in Other Menus

### ISSUE THREAD

**Issue by CuteLuoBo** [poi-vrc/DressingTools#429]
I find the photo-taking feature in the cabinet system very useful. I would like to use the images captured by this feature as icons in other menus, such as for hairstyles or accessories that do not have the cabinet animation enabled. Is there a way to locate or export these images?

DressingTools Version:2.5.0

**Comment by poi-vrc** [comment]
Sorry for late reply, there is no feature yet to directly take photos and export it. I think there is some tools that can already do that.
