### ISSUE TITLE
Feature Request: Adding a New Radial Menu Option in the Cabinet System for Animated Texture/Color Switching

### ISSUE THREAD

**Issue by CuteLuoBo** [poi-vrc/DressingTools#430]
I would like to add a new radial menu option (on the same level as the custom switch) in the cabinet system to support parameter animations for switching clothing textures/colors. 
![20240613](https://github.com/poi-vrc/DressingTools/assets/44561136/ee7df0e9-04e1-4996-a64a-8c04ac454761)
My current approach is to use the Smart Control system, but external menus might confuse users. 
![20240613](https://github.com/poi-vrc/DressingTools/assets/44561136/dc43a845-db54-48cd-b8f4-a9d4b005eb93)
![20240613](https://github.com/poi-vrc/DressingTools/assets/44561136/d3455a2e-2d31-4420-9446-89416653b3fc)

I have tried using the Install component with the cabinet system menu path, but it did not work, possibly due to incorrect implementation. If this approach is viable, I would appreciate any official examples.

**Comment by poi-vrc** [comment]
Sorry for late reply, the cabinet system is migrating to fully controlled by Smart Control soon in later versions. The current way to do that is only to use SmartControls alongside with Menu Installer to install your custom menus into the cabinet menu.
