### ISSUE TITLE
"IgnoreTransforms" not working in 2.5.0

### ISSUE THREAD

**Issue by ilcalmissimo** [poi-vrc/DressingTools#432]
The IgnoreTransforms mapping mode, which is supposed to add bones to the "ignore transforms" list of a physbone, is not working in 2.5.0. Downgrading to 2.4.0 made them work again.

I'm using VRC SDK Base and Avatars 3.7.1

**Comment by poi-vrc** [comment]
Sorry for the delay. The ignoretransform fix will be included in 2.5.1

**Comment by poi-vrc** [comment]
https://github.com/poi-vrc/DressingTools/releases/tag/2.5.1-beta.1
Please try the 2.5.1-beta.1 to see if the issue is solved for you. I will push to 2.5.1 within a week if there is no big issue.
