### ISSUE TITLE
How To Get DressingTools into Unity

### ISSUE THREAD

**Issue by HyliaStar** [poi-vrc/DressingTools#7]
How do I get DressingTools into the project? I imported the package but it does not show up anywhere for me to use.

**Comment by poi-vrc** [comment]
Sorry for the confusion. Once you have imported the package to the project, you can start the DressingTools window from `Tools -> chocopoi -> Dressing Tools`.

**Comment by HyliaStar** [comment]
Thank you so much! I found the tool and was able to successfully use it!
