### ISSUE TITLE
Will not show up after import

### ISSUE THREAD

**Issue by Nosuuddo** [poi-vrc/DressingTools#9]
Hello! Quick issue, I cannot seem to find the tool after importing?
I looked under Tools and Windows but it's not there! D:

I'm running unity 2019.4.31f1 and was not using dynamic bones as my project does not require them as of the VRCK3 Interactions update!

**Comment by poi-vrc** [comment]
Hi, you have to import DynamicBones to use the tools for the time being. Because it requires it to handle placing DynamicBones clothes onto a PhysBone avatar / PhysBone clothes onto a DynamicBone avatar.

I will remove this requirement soon, but it is required to be imported now.
